main: com.ulticraft.stability.Stability
name: Stability
version: 1.5.3
softdepend: [WorldEdit]
loadbefore: [WorldEdit]
commands:
  stability:
    aliases: st
    description: Base Stability Command
  awe:
    description: 'Displays the help for Async world edit.'
    usage: /<command>
    aliases: /awe